[project]
name = "crax-app"
version = "0.1.0"
description = "The social platform for builders"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.120.0",
    "pydantic>=2.12.3",
    "requests>=2.32.5",
    "selenium>=4.38.0",
]
